# site settings
title: nurnice
subtitle: GmbH
email: jonas.hofer@outlook.com
description: Wir liefern Software, die ist einfach nur nice!<br /> Treten Sie mit uns in Kontakt und wir helfen Ihnen für sie die richtige Lösung zu finden.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Seestrasse 139
city: Uster
state: null
zip_code: 8610
country: Switzerland
phone: +41 78 801 17 88

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: 
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
